# Project 10 Test

import money

print('===================')
print('===Start Testing===')
print('===================')
a = money.Amount(56.79, 'USD')
print('a:',a)
b = money.Amount(101.192743233, 'SEK')
print('b:',b)
c = a.convert('GBP')
print('c:',c)
d = c.convert('CHF')
print('d:',d)
e = a.convert('SEK')
print('e:',e)
print('===================')
print('=====Arithmetic====')
print('===================')
print('a+b:',a+b)
print('102.4325+c:',102.4325+c)
print('c+102.4325:',c+102.4325)
print('d-b:',d-b)
print('100-a:',100-a)
print('a-100:',a-100)
print('b==a:',b==a)
print('b!=e:',b!=e)
print('a<c:',a<c)
print('a<=c:',a<=c)
print('===================')
print('======Invalid======')
print('===================')
z = money.Amount(120.20, 'NON')
print(z)
y = money.Amount('test', 'CHF')
print(y)
x = money.Amount('40','test')
print(x)
print('a+"cow":',a+"cow")
print('"test"+c:',"test"+c)
print('a-"two":',a-"two")
print('b=="turkey":',b=='turkey')
print('b!="land":',b!='land')
print('a<"10":',a<'10')
print('a<="dog":',a<="dog")
